# Generated by Django 3.2.4 on 2021-07-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('tree_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('tree_name', models.CharField(max_length=100)),
                ('tree_url', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('xp_plant', models.IntegerField(default=0)),
                ('time_plant', models.IntegerField(default=0)),
                ('version_level', models.CharField(choices=[('V1', 'Version1'), ('V2', 'Version2'), ('V3', 'Version3')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('discord_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('discord_tag', models.CharField(max_length=100)),
                ('avatar', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
                ('xp', models.IntegerField(default=0)),
                ('coins', models.PositiveIntegerField(default=0)),
                ('tress_unlocked', models.ManyToManyField(to='api.Tree')),
            ],
        ),
    ]
